---
jobs:
  - name: docker-broker
    templates:
    - name: docker
    - name: cf-containers-broker
    instances: 1
    resource_pool: docker
    persistent_disk: 65536
    networks:
    - name: default
      static_ips: (( merge ))

  - name: fetch-containers-images
    template: fetch-containers-images
    instances: 1
    resource_pool: errand
    lifecycle: errand
    networks:
      - name: default

  - name: broker-registrar
    template: broker-registrar
    instances: 1
    resource_pool: errand
    lifecycle: errand
    networks:
    - name: default

  - name: broker-deregistrar
    template: broker-deregistrar
    instances: 1
    resource_pool: errand
    lifecycle: errand
    networks:
    - name: default
