---
meta:
  cpi-release: (( merge ))

  bosh_private_ip: (( merge || nil ))

  bosh_public_ip: (( merge ))

  bosh_service_ip: (( merge ))

name: (( merge ))

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=207
  sha1: 5f835bad5fc46230cd2fa823c0a52a94829ee044
- (( meta.cpi-release ))


resource_pools: (( merge ))

disk_pools: (( merge ))

networks: (( merge ))

jobs: (( merge ))

properties: (( merge || nil ))

cloud_provider: (( merge ))

