---
meta:
  cpi-release: (( merge ))

  bosh_private_ip: (( merge || nil ))

  bosh_public_ip: (( merge ))

  bosh_service_ip: (( merge ))

  ntp: (( merge ))

  default_bosh_private_static_ips:
    - (( meta.bosh_private_ip ))
  default_bosh_public_static_ips:
    - (( meta.bosh_public_ip ))

  default_bosh_job_templates:
    - {name: nats, release: bosh}
    - {name: redis, release: bosh}
    - {name: postgres, release: bosh}
    - {name: blobstore, release: bosh}
    - {name: director, release: bosh}
    - {name: health_monitor, release: bosh}

  specific_bosh_job_templates: (( merge ))

name: (( merge ))

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=207
  sha1: 5f835bad5fc46230cd2fa823c0a52a94829ee044
- (( meta.cpi-release ))


resource_pools: (( merge ))

disk_pools:
- name: disks
  disk_size: 32_768
  cloud_properties: (( merge ))

networks: (( merge ))

jobs:
- name: bosh
  instances: 1

  templates: (( meta.default_bosh_job_templates meta.specific_bosh_job_templates ))

  networks:
  - name: private
    static_ips: (( merge || meta.default_bosh_private_static_ips ))
    default: [dns, gateway]
  - name: public
    static_ips: (( merge || meta.default_bosh_public_static_ips ))


properties: (( merge || nil ))

cloud_provider:
  template: (( merge ))

  ssh_tunnel:
    host: (( meta.bosh_service_ip ))
    port: 22
    user: vcap
    private_key: .ssh/id_rsa

  mbus: (( "https://mbus:mbus@" meta.bosh_service_ip  ":6868" ))

  properties: (( merge ))
