---
meta:

  bosh_private_ip: (( merge || nil ))

  bosh_public_ip: (( merge ))

  bosh_service_ip: (( merge ))

name: (( merge ))

releases: (( merge ))

resource_pools: (( merge ))

disk_pools: (( merge ))

networks: (( merge ))

jobs: (( merge ))

properties: (( merge || nil ))

cloud_provider: (( merge ))

