name: ((merge))
meta:
  zones:
    z1: (( properties.template_only.gce.availability_zone ))
    z2: (( properties.template_only.gce.availability_zone2 ))

  stemcell:
    name: bosh-google-kvm-ubuntu-trusty-go_agent
    version: latest
properties:
  <<: (( merge ))

  logger_endpoint:
    port: 443

  loggregator:
    blacklisted_syslog_ranges:
    - start: 10.10.0.0
      end: 10.10.255.255

  uaa:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m

networks: (( merge ))

resource_pools:
  - name: small_z1
    cloud_properties:
      machine_type: n1-standard-4
      root_disk_size_gb: 10
      root_disk_type: pd-standard
      zone: (( meta.zones.z1 ))

  - name: small_z2
    cloud_properties:
      machine_type: n1-standard-4
      root_disk_size_gb: 10
      root_disk_type: pd-standard
      zone: (( meta.zones.z2 ))

  - name: medium_z1
    cloud_properties:
      machine_type: n1-standard-4
      root_disk_size_gb: 10
      root_disk_type: pd-standard
      zone: (( meta.zones.z1 ))

  - name: medium_z2
    cloud_properties:
      machine_type: n1-standard-4
      root_disk_size_gb: 10
      root_disk_type: pd-standard
      zone: (( meta.zones.z2 ))

  - name: large_z1
    cloud_properties:
      machine_type: n1-standard-8
      root_disk_size_gb: 65
      root_disk_type: pd-standard
      zone: (( meta.zones.z1 ))

  - name: large_z2
    cloud_properties:
      machine_type: n1-standard-8
      root_disk_size_gb: 65
      root_disk_type: pd-standard
      zone: (( meta.zones.z2 ))

  - name: runner_z1
    cloud_properties:
      machine_type: n1-standard-8
      root_disk_size_gb: 100
      root_disk_type: pd-standard
      zone: (( meta.zones.z1 ))

  - name: runner_z2
    cloud_properties:
      machine_type: n1-standard-8
      root_disk_size_gb: 100
      root_disk_type: pd-standard
      zone: (( meta.zones.z2 ))

  - name: router_z1
    cloud_properties:
      machine_type: n1-standard-4
      root_disk_size_gb: 10
      root_disk_type: pd-standard
      zone: (( meta.zones.z1 ))

  - name: router_z2
    cloud_properties:
      machine_type: n1-standard-4
      root_disk_size_gb: 10
      root_disk_type: pd-standard
      zone: (( meta.zones.z2 ))

  - name: small_errand
    cloud_properties:
      machine_type: n1-standard-4
      root_disk_size_gb: 10
      root_disk_type: pd-standard
      zone: (( meta.zones.z1 ))

  - name: xlarge_errand
    cloud_properties:
      machine_type: n1-highcpu-8
      root_disk_size_gb: 65
      root_disk_type: pd-standard
      zone: (( meta.zones.z1 ))

compilation:
  cloud_properties:
    machine_type: n1-highcpu-8
    availability_zone: (( meta.zones.z1 ))

