---
terraform_outputs: (( merge ))
secrets: (( merge ))
name: (( "cloudfoundry-" meta.environment ))
meta:
  environment: (( terraform_outputs.environment ))
  zones:
    z1: (( terraform_outputs.zone0 ))
    z2: (( terraform_outputs.zone1 ))
  fog_config:
    region: (( terraform_outputs.region ))

  consul_servers:
     - (( "0.consul-z1.cf1." .name ".microbosh" ))

networks:
  - name: cf1
    type: dynamic
    cloud_properties:
      network_name: (( terraform_outputs.cf1_network_name ))
      ephemeral_external_ip: false
      tags:
        - cf
        - (( terraform_outputs.environment ))
        - (( name ))

  - name: cf2
    type: dynamic
    cloud_properties:
      network_name: (( terraform_outputs.cf2_network_name ))
      ephemeral_external_ip: false
      tags:
        - cf
        - (( terraform_outputs.environment ))
        - (( name ))

  - name: router1
    type: dynamic
    cloud_properties:
      network_name: (( terraform_outputs.cf1_network_name ))
      ephemeral_external_ip: false
      tags:
        - cf
        - (( terraform_outputs.environment ))
        - (( name ))
      target_pool: (( terraform_outputs.router_pool_name ))

  - name: router2
    type: dynamic
    cloud_properties:
      network_name: (( terraform_outputs.cf2_network_name ))
      ephemeral_external_ip: false
      tags:
        - cf
        - (( terraform_outputs.environment ))
        - (( name ))
      target_pool: (( terraform_outputs.router_pool_name ))

properties:
  graphite:
    server: (( "0.graphite.cf1." .name ".microbosh" ))
  domain: (( terraform_outputs.environment ".cf2.paas.alphagov.co.uk" ))
  collector:
    graphite:
      address: (( "0.graphite.cf1." .name ".microbosh" ))
  template_only:
    gce:
      availability_zone: (( terraform_outputs.zone0 ))
      availability_zone2: (( terraform_outputs.zone1 ))

  dea_next:
    mtu: 1460

  databases:
    address: (( "0.postgres-z1.cf1." .name ".microbosh" ))

  syslog_daemon_config:
    address: (( "0.logsearch-minimal.default.logsearch-" meta.environment ".microbosh" ))
    port: 2514
    transport: relp

jobs:
  - name: router_z1
    networks:
      - name: router1
        static_ips: null

  - name: router_z2
    networks:
      - name: router2
        static_ips: null

  - name: postgres_z1
    instances: 1

resource_pools:
  - name: router_z1
    network: router1
  - name: router_z2
    network: router2
