name: (( merge ))

jobs:
  - <<: (( merge ))

meta:
  collector:
    intervals:
      default: 10

properties:
  <<: (( merge ))
  collector:
    deployment_name: (( name ))
    use_graphite: true
    graphite:
      address: changeme
      port: 2003
    intervals:
      healthz: (( meta.collector.intervals.default ))
      local_metrics: (( meta.collector.intervals.default ))
      nats_ping: (( meta.collector.intervals.default ))
      varz: (( meta.collector.intervals.default ))
