---
terraform_outputs: ((merge))
director_uuid: BOSH_UUID
name: (( "cloudfoundry-" meta.environment ))
meta:
  environment: (( terraform_outputs.environment ))

update:
  serial: false # makes every job deploy at the same time.

jobs:
  - name: runner_z1
    instances: 1
  - name: runner_z2
    instances: 1
  - name: consul_z1
    instances: 1


properties:
  cc:
    staging_upload_user: username
    min_cli_version: '6.1.0'
    min_recommended_cli_version: '6.10.0'
  nats:
    user: nats_user
  dea_next:
    disk_mb: 10240
    memory_mb: 4096
  router:
    enable_ssl: true
    cipher_suites: TLS_RSA_WITH_RC4_128_SHA:TLS_RSA_WITH_AES_128_CBC_SHA
    status:
      user: router_user
  uaa:
    batch:
      username: batch_username
  login:
    links:
      network: https://network.gopivotal.com/login
      signup-network: https://network.gopivotal.com/registrations/new
    smtp:
      host: localhost
      port: 2525
