terraform_outputs: (( merge ))
meta:
  zones:
    z1: (( terraform_outputs.zone0 ))
    z2: (( terraform_outputs.zone1 ))

resource_pools:
  - name: graphite_z1
    cloud_properties:
      instance_type: m3.large
      ephemeral_disk:
        size: 65_536
        type: gp2
      availability_zone: (( meta.zones.z1 ))
      elbs:
      - (( terraform_outputs.graphite_elb_name ))

jobs:
  - name: graphite
    instances: 1
    persistent_disk: 204800
    networks:
    - name: cf1
      static_ips: [ 10.0.10.40 ]
